### ISSUE TITLE
Can't configure protobuf compilation to follow gRPC standard

### ISSUE THREAD

**Issue by jperkelens** [micro/protoc-gen-micro#3]
After looking into this repo and the [go-grpc repo](https://github.com/micro/go-grpc). I'm having trouble figuring out how to generate files that creates a service that follow the gRPC standard for operation naming rather than micro's proprietary naming (slashes vs dots)

The current command I'm using is `protoc --micro_out=plugins=grpc:. --go_out=. proto/*.proto`.
I've also tried `protoc --micro_out=plugins=grpc:. --go_out=plugins=grpc:. proto/*.proto` and that generates duplicative handlers.

 It feels like im missing something enormously simple, but I cant find any documentation around this.

**Comment by asim** [comment]
Go-grpc uses micro generated protos not the grpc plugin. Do not specify grpc as a plugin.

**Comment by asim** [comment]
> What I really am looking for is an option to get the boilerplate code to conform to gRPC standard.

This won't happen. We're generating code for go-micro. Look at the generated code. We're creating code that would otherwise have to be written by the developer. That's the purpose of it. 

If you want to generate grpc code, generate it and use the [grpc-go](https://github.com/grpc/grpc-go) framework. The issue of slash delimited vs dot is irrelevant as micro's grpc client and server do the translation on the fly.

I'd advise you to go directly to [grpc-go](https://github.com/grpc/grpc-go) since that's what you're looking for.

**Comment by jperkelens** [comment]
Alright, thanks for the replies. I'm not really sure how you can say you support a protocol when you don't conform to standards, but I'll try to configure my clients appropriately.

**Comment by asim** [comment]
As I mentioned we do conform to the standard. GRPC is a wire protocol. We support its wire protocol. On the wire we send `/package.Service/Method`. Just because you do not see this in our generated protos does not mean we don't support it. Our code for the client is [here](https://github.com/micro/go-plugins/tree/master/client/grpc). Our code for the server is [here](https://github.com/micro/go-plugins/tree/master/server/grpc). Here is the [method](https://github.com/micro/go-plugins/blob/master/client/grpc/request.go#L19L43) that translates method names. 

Realise that the grpc-go framework is an implementation of the grpc protocol. Our framework go-grpc doesn't support the grpc-go framework or its generated code, it supports the grpc protocol. Look at the grpc generated code, its for the grpc-go framework. 

Again please go use the grpc-go framework. It'll be easier for you.

**Comment by jperkelens** [comment]
If that's the case, I suggest that you have a bug in your server code, because i keep getting malformed method name errors when trying to consume it unless i manually do the method translation.

**Comment by asim** [comment]
Do you have an example of this? Because the example code we have should run fine and interoperate with grpc-go based services.

**Comment by jperkelens** [comment]
I'll try to recreate it in a toy example tonight.

**Comment by jperkelens** [comment]
Here's a repo where you can see the observed behavior:

https://github.com/jperkelens/micro-path-example

**Comment by asim** [comment]
It's a fairly trivial issue. Method name is `/Hello/Greet` when we're expecting `/package.Hello/Greet`.

Most examples of gRPC include "package" in the proto which outputs the correct methods. Our mapper assumes package will always be present for gRPC names. The fix is fairly simple on the server side code. I'll do this later.

**Comment by asim** [comment]
The issue is fixed, your example works fine now.
