### ISSUE TITLE
New version broke all of our projects.

### ISSUE THREAD

**Issue by gyurobenjamin** [micro/protoc-gen-micro#7]
0.3.0 version got lot of broken changes. The client interfaces has been renamed etc.

Not we need to fix all our codebases or figure out how to use the old version.

**Comment by gyurobenjamin** [comment]
{Servicename}Client interface has been renamed to {Servicename}Service interface....

**Comment by asim** [comment]
Protoc-gen-micro is an optional tool to generate code to reduce boilerplate. Feel free not to use it or write your own to do the same. Otherwise feel free to pin the version you're using. 

This change was made because we conflicted with grpc generated types. It's something we had to rectify to interoperate with grpc long term.

**Comment by asim** [comment]
Closing. We're fixing a service stutter issue but for all intents and purposes the rename sticks. Please use old versions if its an issue. Otherwise use a tool like https://golang.org/cmd/fix/ to update references.
